---
title: "BGS PCA"
author: "Kelly Murman"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r load packages, include = F}

library(FactoMineR)
library(factoextra)
library(vegan)
library(tidyverse)
library(ggrepel)
library(corrplot)

```

```{r load data, include = F}

bgsxsals <- read.csv("BGS x Gut Contents.csv")

```


```{r BGS x gut contents}
str(bgsxsals)
bgsxsals$site <- as.factor(bgsxsals$site)
bgsxsals$season <- as.factor(bgsxsals$season)
bgsxsals$samp.type1 <- as.factor(bgsxsals$samp.type1)
bgsxsals$samp.type2 <- as.factor(bgsxsals$samp.type2)

#remove individual species, all salamanders pooled
bgsxsals_sp <- bgsxsals %>%
  select(!samp.type1)

bgsxsals.pca <- PCA(bgsxsals_sp, quali.sup = 1:3, graph = T)

# none of these work to remove the labels...
plotellipses(bgsxsals.pca, invisible = "group", label = FALSE)


plotellipses(bgsxsals.pca, invisible = "group")


plotellipses(bgsxsals.pca, label = "none")

#still labeled
#plotellipses(bgsxsals.pca, habillage = as.factor(bgsxsals$samp.type2), label = FALSE)

get_eig(bgsxsals.pca)

fviz_screeplot(bgsxsals.pca, addlabels = TRUE, ylim = c(0,15))

# extract the results for variables
var2 <- get_pca_var(bgsxsals.pca)
var2

# coordinates of variables
head(var2$coord)
varcoord2 <- head(var2$coord, 96)

# contribution of variables
varcontrib <- head(var$contrib, 84)

fviz_pca_var(bgsxsals.pca, col.var = "cos2", gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), repel = TRUE)

# contributions of variables to PC1
fviz_contrib(bgsxsals.pca, choice = "var", axes = 1, top = 10)

# contributions of variables to PC2
fviz_contrib(bgsxsals.pca, choice = "var", axes = 2, top = 10)

fviz_pca_biplot(bgsxsals.pca, label = "var", select.var = list(contrib = 10),
                habillage = as.factor(bgsxsals_sp$samp.type2), addEllipses = TRUE, repel = TRUE,
                palette = c("#002D04", "#BCECAC", "#0ABAB5", "#FFDF00", "#FF0000", "#7F4B89"))


# do we need this anywhere?
bgsxsalsbysp <- bgsxsals %>%
  select(!samp.type1)

bgsxsalsbysp.pca <- PCA(bgsxsalsbysp, quali.sup = 1:3, graph = T)

plotellipses(bgsxsalsbysp.pca)


```


#Analysis of Similarities (ANOSIM)

```{r ANOSIM}
# "bray" is the dissimilarity measure (Bray-Curtis)

bgsxsals_nozero <- bgsxsals %>%
  rowwise() %>%
  filter(sum(c_across(Acalyptratae:Trichoptera)) != 0)

bgsxsals_com <- bgsxsals_nozero[,5:ncol(bgsxsals_nozero)]

bgsxsals_com <- as.matrix(bgsxsals_com)

anosim(x = bgsxsals_com, grouping = bgsxsals_nozero$site, permutations = 9999,
       distance = "bray")

anosim(x = bgsxsals_com, grouping = bgsxsals_nozero$season, permutations = 9999,
       distance = "bray")

anosim(x = bgsxsals_com, grouping = bgsxsals_nozero$samp.type1, permutations =
         9999, distance = "bray")

anosim(x = bgsxsals_com, grouping = bgsxsals_nozero$samp.type2, permutations =
         9999, distance = "bray")


```


#PCA with taxa separated by age class. Don't worry about this for now.


```{r PCA with taxa by age class}

agebacksamps <- agebacksamps[, -5]

agebacksamps.pca <- PCA(agebacksamps, quali.sup = 1:4, graph = T)

plotellipses(agebacksamps.pca)

get_eig(agebacksamps.pca)

fviz_screeplot(agebacksamps.pca, addlabels = TRUE, ylim = c(0,15))

## extract the results for variables
agevar <- get_pca_var(agebacksamps.pca)
agevar

## coordinates of variables
head(agevar$coord)
ageeigenvalues <- head(agevar$coord, 70)
ageeigenvalues

## contribution of variables
head(agevar$contrib, 70)

## graph of variables: default plot
fviz_pca_var(agebacksamps.pca, col.var = "black")

## control variable colors using their contributions
fviz_pca_var(agebacksamps.pca, col.var = "contrib",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), repel = TRUE) ##avoid text overlapping

## contributions of variables to PC1
fviz_contrib(agebacksamps.pca, choice = "var", axes = 1, top = 10)

## contributions of variables to PC2
fviz_contrib(agebacksamps.pca, choice = "var", axes = 2, top = 10)

## extract the results for individuals
ageind <- get_pca_ind(agebacksamps.pca)
ageind

## coordinates of individuals
head(ageind$coord)

## graph of individuals
## 1. use repel = TRUE to avoid overplotting
## 2. control automatically the color of individuals using the cos2
  # cos2 = the quality of the individuals on the factor map
  # use points only
## 3. use gradient color
fviz_pca_ind(agebacksamps.pca, col.ind = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), repel = TRUE)

## biplot of individuals and variables
fviz_pca_biplot(agebacksamps.pca, repel = TRUE)

## color coded graph of individuals
fviz_pca_ind(agebacksamps.pca, label = "none", habillage = as.factor(agebacksamps$Site), palette = c("#00AFBB", "#E7B800", "#FC4E07", "#032d70"), addEllipses = TRUE)

fviz_pca_ind(agebacksamps.pca, label = "none", habillage = as.factor(agebacksamps$Season), palette = c("#00AFBB", "#E7B800", "#FC4E07", "#032d70"), addEllipses = TRUE)

fviz_pca_ind(agebacksamps.pca, label = "none", habillage = as.factor(agebacksamps$Samp.Type), palette = c("#00AFBB", "#E7B800", "#FC4E07", "#032d70"), addEllipses = TRUE)

fviz_pca_ind(agebacksamps.pca, label = "none", habillage = as.factor(agebacksamps$Age.Class), palette = c("#00AFBB", "#E7B800", "#FC4E07", "#032d70"), addEllipses = TRUE)

```

# Analysis of Similarities with age class as a factor

```{r ANOSIM w age class}
agecom <- agebacksamps[,5:ncol(agebacksamps)]

m_agecom <- as.matrix(agecom)

anosim(x = m_com, grouping = agebacksamps$Site, permutations = 999, distance = "bray")

anosim(x = m_com, grouping = agebacksamps$Season, permutations = 999, distance = "bray")

anosim(x = m_com, grouping = agebacksamps$Samp.Type, permutations = 999, distance = "bray")

anosim(x = m_com, grouping = agebacksamps$Age.Class, permutations = 999, distance = "bray")



```

## Stef's code using vegan for PCA

```{r vegan pca code, include = F}

pca_1 <- rda(backsamps[,5:ncol(backsamps)])
summary(pca_1)

taxa <- scores(pca_1, display = "species", scaling = 1)
site <- scores(pca_1, display = "sites", scaling = 1)

site_scores <- as.data.frame(site)
taxa <- as.data.frame(taxa)

site_scores$site <- backsamps$site
site_scores$season <- backsamps$season
site_scores$type <- backsamps$samp.type
site_scores$point <- backsamps$samp.point

backsamps$PC1 <- site_scores[,1]
backsamps$PC2  <- site_scores[,2]

hull <- backsamps %>% group_by(season) %>%
slice(chull(PC1, PC2))


pal <- c("#920000", "#db6d00","#009292")


# plot_sites <-
#   ggplot(env_var, aes(x = RDA1, y = RDA2)) +
#   #first site points, colored by a factor here - survey number
#   geom_point(aes(color = as_factor(env_var$survey_number), size = 3)) +
#   # I had issues with coloring - I tried to use the palette above (pal) but it wasn't working out for me since I wanted to color different elements on this figure so instead I manually filled in the colors. you should be able to set a palette and then call that palette name for fill or color
#   scale_color_manual(values = c("#920000", "#009292", "#db6d00")) +
#   labs(y = paste0("RDA1 (", round(abun_rda_final$CCA$eig[1] *10, 2), "%)"),
#        x = paste0("RDA2 (", round(abun_rda_final$CCA$eig[2] * 10, 2), "%)"),
#        title = "RDA Biplot - Site Scores") +
#   #then polygons
#   geom_polygon(data = hull, alpha = 0.01,
#                  aes(colour = as_factor(survey_number),
#                      fill = as_factor(survey_number)), show.legend = F) +
#   #then "species" points
#   geom_point(data = species_scores, aes(x = RDA2, y = RDA1,
#                                         fill = "black", size = 3), show.legend = F) +
#   geom_label_repel(data = species_scores, aes(x = RDA2, y = RDA1, label = rownames(species_scores)),
#                    size = 5, direction = "both", max.overlaps = 20, show.legend = F, label.size = NA) +
#   #below is for arrows - you don't need this
#   geom_segment(data = as.data.frame(abun_rda_final$CCA$biplot),
#                aes(x = 0, y = 0, xend = RDA2 * 1, yend = RDA1 * 1),
#                arrow = arrow(length = unit(0.5, "cm")), size = 2, color = "#004949", show.legend = F) +
#   # labeling the arrows - not needed
#   geom_label(data = as.data.frame(abun_rda_final$CCA$biplot),
#              aes(x = RDA2 * .8, y = RDA1 * .8, label = c("Temperature", "SLF Fitted")),
#              color = "#004949", vjust = "bottom" , hjust = 0.8, show.legend = F, label.size = NA) +
#   #this theme just makes it look simple and clean - look up other themes! such as theme_bw()
#    theme_minimal()   +
#   #labeling the legend
#   labs(colour = "Survey Number") +
#   #changing text side of title and in figure text
#   theme(legend.title = element_text(size = 14),
#         legend.text = element_text(size = 12)) +
#   #this removes the legend but may be a bit wonky at times
#   guides(size= "none")



plot_sites <- 
  ggplot(site_scores, aes(x = PC1, y = PC2)) +
  geom_point(aes(color = season, size = 1)) +
  geom_label_repel(aes(x = PC1, y = PC2, label = site_scores$site), 
                   size = 5, direction = "both", max.overlaps = 20, show.legend = F, label.size = NA) 
  # geom_polygon(data = hull, alpha = 1,
  #                aes(colour = as_factor(season),
  #                    fill = as_factor(season)), show.legend = F) +
  # #then "species" points
  # geom_point(data = taxa, aes(x = PC1, y = PC2, 
  #                                       fill = "black", size = 1), show.legend = F) +
  #  theme_minimal()   +
  # #labeling the legend
  # labs(colour = "seasonr") + 
  # #changing text side of title and in figure text
  # theme(legend.title = element_text(size = 14),
  #       legend.text = element_text(size = 12)) +
  # #this removes the legend but may be a bit wonky at times
  # guides(size= "none")  



plot_sites


```

```{r}



```

