---
title: "Diet Analyses"
author: "Kelly Murman"
date: "`r Sys.Date()`"
output: html_document
---

#Load libraries
```{r load packages}

library(tidyverse)
library(vegan)
library(stats)
library(ggpubr)
library(FSA)
library(car)
library(factoextra)
library(FactoMineR)

```

#Load data

```{r load data}
saldata_raw <- read.csv("MASTER SPECIMEN CATALOG.csv")

background <- read.csv("BGS MASTER LIST.csv")

```

#Make summary table of diet volume and number by diet environment per salamander

```{r yee haw}
#remove duplicates for SVL data
SVL <- saldata_raw %>% select(SPECIES, SPECIMEN.ID, SVL) %>%
  distinct()

#filtering steps
##keep only SAMPLING.METHOD == Flushed
##remove TAXA == Unidentifiable Insect Parts *and* No gut contents
##group by SPECIMEN.ID *and* PREY.CATEGORY
##summarize total VOLUME


dietvolume <- saldata_raw %>%
  filter(SAMPLING.METHOD %in% c('Flushed')) %>%
  filter(!TAXA %in% c('Unidentifiable Insect Parts', 'No gut contents')) %>%
  group_by(SITE, SEASON, SPECIES, SVL, SPECIMEN.ID, PREY.CATEGORY) %>%  #add whatever columns need to be kept
  summarize(VOLUME = sum(VOLUME))


#separate prey category into columns, add value = 0 for any prey categories not observed for a specimen
dietvolume_by_category <- dietvolume %>%
  pivot_wider(names_from = PREY.CATEGORY,
              values_from = VOLUME,
              values_fill = 0,
              names_prefix= "volume_")

#remove temp file
rm(dietvolume) 

#add total volume and calculate proportional volume for each prey category
dietvolume_by_category <- dietvolume_by_category %>%
  mutate(volume_total = sum(c_across(starts_with("volume")), na.rm=T)) %>%
  mutate(prop_aquatic = volume_aquatic/volume_total, 
         prop_terrestrial = volume_terrestrial/volume_total, 
         prop_intermediate = volume_intermediate/volume_total, 
         prop_neither = volume_neither/volume_total) %>%
  mutate(aquatic_binary = ifelse(volume_aquatic > 0, "1", "0"))

dietvolume_by_category$aquatic_binary <- as.numeric(dietvolume_by_category$aquatic_binary)
dietvolume_by_category <- as_tibble(dietvolume_by_category)
#from here, glm of aquatic_binary ~ SPECIES, family = binomial
#then, filter new table to just the values binary = 1, do old glm just on those (prop aquatic diffs given that there was any aquatic)

#trying to get R to count the number of times each prey category is consumed by each individual salamander to replicate the GLM that had significant results
#I want to get R to do this, but for the sake of getting this analysis done, I am uploading the csv
#dietnumber <- saldata_raw %>%
 # filter(SAMPLING.METHOD %in% c('Flushed')) %>%
  #filter(!TAXA %in% c('Unidentifiable Insect Parts', 'No gut contents')) %>%
  #group_by(SITE, SEASON, SPECIES, SVL, SPECIMEN.ID, PREY.CATEGORY) %>%
  #group_by()


dietcount_by_category <- saldata_raw %>%
  filter(SAMPLING.METHOD %in% c('Flushed')) %>%
  filter(!TAXA %in% c('Unidentifiable Insect Parts', 'No gut contents')) %>%
  group_by(SITE, SEASON, SPECIES, SVL, SPECIMEN.ID, PREY.CATEGORY) %>%
  summarize(n = n()) %>% #  n = n means it's counting the number of observations i.e. the rows
  pivot_wider(names_from = PREY.CATEGORY, 
              values_from = n,
              values_fill = 0,
              names_prefix = "count_") %>%
  mutate(count_total = sum(c_across(starts_with("count")), na.rm=T)) %>%
  mutate(propcount_aquatic = count_aquatic/count_total, 
         propcount_terrestrial = count_terrestrial/count_total, 
         propcount_intermediate = count_intermediate/count_total, 
         propcount_neither = count_neither/count_total)
```


workflow for background sample count by prey category comparison
```{r}
#keep counts from prey_category_count
#group by season
#sum total number prey eaten within each category for each season

dietcount_totals_by_szn <- dietcount_by_category %>%
  group_by(SEASON) %>%
  summarize(total_aquatic = sum(count_aquatic),
            total_terrestrial = sum(count_terrestrial),
            total_intermediate = sum(count_intermediate),
            total_neither = sum(count_neither))


#from background samples
#group by season
#sum total number prey items observed from each prey category for each season

#keep this as background summary
BGScount_totals_by_szn <- background %>%
  group_by(season, prey_category) %>%
  summarize(count = sum(number_individuals)) %>%
  pivot_wider(names_from = "prey_category",
              values_from = "count",
              names_prefix = "total_")



#get total prey eaten (sum of all categories) from salamanders - per season
#get total prey items documented (sum of all categories) from background - per season
#get proportion of total prey items documented from each category (prop of total) - per season




#calculate 'expected' number of prey eaten based on the total documented and category proportions

#chi squared - salamander diets are observed, background estimated counts from proportions are expected
```

#stats


```{r GLM on percent aquatic prey volume}

# GLM on the proportion of VOLUME of prey type consumed
# N.S.

volume_glm <- car::Anova(glm(formula = volume_aquatic ~ SPECIES + SVL + SEASON,
                      data = dietvolume_by_category), type = 3)

volume_glm



#keep this glm, this one is now consistent with kw, it's the prop zeroes

volume_glm2 <- car::Anova(glm(formula = aquatic_binary ~ SPECIES + SVL + SEASON,
                      data = dietvolume_by_category, family = binomial), type = 3)

volume_glm2


# GLM on the proportion of NUMBER of prey type consumed
# significant for season (p = 0.03)

number_glm <- car::Anova(glm(formula = propcount_aquatic ~ SPECIES + SVL + SEASON,
                      data = dietcount_by_category, family = binomial), type = 3)
number_glm
                          

# VOLUME aquatic ~ SPECIES
kruskal.test(volume_aquatic ~ SPECIES,
             data = dietvolume_by_category)

dunnTest(volume_aquatic ~ SPECIES,
         data = dietvolume_by_category)
```

```{r KW on VOLUME}
kruskal.test(SVL ~ SPECIES,
             data = SVL)

dunnTest(SVL ~ SPECIES,
         data = SVL)

#KW examining VOLUME of prey cat consumed as a function of SPECIES

# VOLUME aquatic ~ SPECIES
kruskal.test(volume_aquatic ~ SPECIES,
             data = dietvolume_by_category)

dunnTest(volume_aquatic ~ SPECIES,
         data = dietvolume_by_category)

# VOLUME intermediate ~ SPECIES
kruskal.test(volume_intermediate ~ SPECIES,
             data = dietvolume_by_category)

dunnTest(volume_intermediate ~ SPECIES,
         data = dietvolume_by_category)

# VOLUME terrestrial ~ SPECIES
kruskal.test(volume_terrestrial ~ SPECIES,
             data = dietvolume_by_category)

dunnTest(volume_terrestrial ~ SPECIES,
         data = dietvolume_by_category)

# VOLUME neither ~ SPECIES
kruskal.test(volume_neither ~ SPECIES,
             data = dietvolume_by_category)

dunnTest(volume_neither ~ SPECIES,
         data = dietvolume_by_category)


#KW examining VOLUME of prey cat consumed as a function of SVL
#running a dunn test using SVL seems like a lot?

# VOLUME aquatic ~ SVL (p = 0.55)
kruskal.test(volume_aquatic ~ SVL,
             data = dietvolume_by_category)

# VOLUME intermediate ~ SVL (p = 0.6)
kruskal.test(volume_intermediate ~ SVL,
             data = dietvolume_by_category)

# VOLUME terrestrial ~ SVL (p = 0.71)
kruskal.test(volume_terrestrial ~ SVL,
             data = dietvolume_by_category)

# VOLUME neither ~ SVL (p = 0.39)
kruskal.test(volume_neither ~ SVL,
             data = dietvolume_by_category)

```

```{r KW on NUMBER}

#KW looking at NUMBER (total count) of prey cat consumed as function of SPECIES

# NUMBER aquatic ~ SPECIES ( p = 0.03)
kruskal.test(count_aquatic ~ SPECIES,
             data = dietcount_by_category)

# not significant??
dunnTest(count_aquatic ~ SPECIES,
         data = dietcount_by_category)

# NUMBER intermediate ~ SPECIES (p = 0.77)
kruskal.test(count_intermediate ~ SPECIES,
             data = dietcount_by_category)


# NUMBER terrestrial ~ SPECIES (p = 0.0001)
kruskal.test(count_terrestrial ~ SPECIES,
             data = dietcount_by_category)

# significant for DF compared to EB** 
dunnTest(count_terrestrial ~ SPECIES,
         data = dietcount_by_category)

kruskal.test(count_neither ~ SPECIES,
             data = dietcount_by_category)


#KW PROPORTION NUMBER ~ SPECIES
kruskal.test(propcount_aquatic ~ SPECIES,
             data = dietcount_by_category)

dunnTest(propcount_aquatic ~ SPECIES,
         data = dietcount_by_category)

kruskal.test(propcount_intermediate ~ SPECIES,
             data = dietcount_by_category)

kruskal.test(propcount_terrestrial ~ SPECIES,
             data = dietcount_by_category)

dunnTest(propcount_terrestrial ~ SPECIES,
         data = dietcount_by_category)

kruskal.test(propcount_neither ~ SPECIES,
             data = dietcount_by_category)



#KW examining NUMBER of prey cat consumed as a function of SEASON
# all significant
kruskal.test(count_aquatic ~ SEASON,
             data = dietcount_by_category)

dunnTest(count_aquatic ~ SEASON,
         data = dietcount_by_category)

kruskal.test(count_intermediate ~ SEASON,
             data = dietcount_by_category)

kruskal.test(count_terrestrial ~ SEASON,
             data = dietcount_by_category)

kruskal.test(count_neither ~ SEASON,
             data = dietcount_by_category)

dunnTest(count_neither ~ SEASON,
         data = dietcount_by_category)

#KW proportion NUMBER ~ SEASON

kruskal.test(propcount_aquatic ~ SEASON,
             data = dietcount_by_category)

dunnTest(propcount_aquatic ~ SEASON,
         data = dietcount_by_category)

kruskal.test(propcount_intermediate ~ SEASON,
             data = dietcount_by_category)

kruskal.test(propcount_terrestrial ~ SEASON,
             data = dietcount_by_category)

dunnTest(propcount_terrestrial ~ SEASON,
         data = dietcount_by_category)

kruskal.test(propcount_neither ~ SEASON,
             data = dietcount_by_category)

dunnTest(propcount_neither ~ SEASON,
         data = dietcount_by_category)


#not sure why this figure is here?
#feels like species should be represented somehow, even though there was no significant difference in proportion aquatic prey consumed between species..
ggplot(dietvolume_by_category,
  aes(x = SPECIES, y = prop_aquatic)) +
  geom_jitter(width = 0.01, size = 8, alpha = 0.05) +
  ggtitle("Proportion Aquatic Prey Number")

```
