---
title: "EJR Data Wrangling"
author: "EJR"
date: "2024-10-04"
output: html_document
editor_options: 
  chunk_output_type: console
---

#Load libraries
```{r load packages}
library(tidyverse)
library(vegan)
library(stats)
library(ggpubr)
library(FSA)
library(car)
```

#Load data

```{r load data}
saldata_raw <- read.csv("MASTER SPECIMEN CATALOG.csv")

#see notes in sections below re: GLM
dietnumber <- read.csv("diet ANOVA % aquatic.csv")

```


#Make summary table of diet volume and number by diet environment per salamander

```{r yee haw}
#remove duplicates for SVL data
SVL <- saldata_raw %>% select(SPECIES, SPECIMEN.ID, SVL) %>%
  distinct()

#filtering steps
##keep only SAMPLING.METHOD == Flushed
##remove TAXA == Unidentifiable Insect Parts *and* No gut contents
##group by SPECIMEN.ID *and* PREY.CATEGORY
##summarize total VOLUME


dietvolume <- saldata_raw %>%
  filter(SAMPLING.METHOD %in% c('Flushed')) %>%
  filter(!TAXA %in% c('Unidentifiable Insect Parts', 'No gut contents')) %>%
  group_by(SITE, SEASON, SPECIES, SVL, SPECIMEN.ID, PREY.CATEGORY) %>%  #add whatever columns need to be kept
  summarize(VOLUME = sum(VOLUME))


#separate prey category into columns, add value = 0 for any prey categories not observed for a specimen
dietvolume_by_preycategory <- dietvolume %>%
  pivot_wider(names_from = PREY.CATEGORY,
              values_from = VOLUME,
              values_fill = 0,
              names_prefix= "volume_")

#add total volume and calculate proportional volume for each prey category
volume_diet_prop <- dietvolume_by_preycategory %>%
  mutate(volume_total = sum(c_across(starts_with("volume")), na.rm=T)) %>%
  mutate(prop_aquatic = volume_aquatic/volume_total, 
         prop_terrestrial = volume_terrestrial/volume_total, 
         prop_intermediate = volume_intermediate/volume_total, 
         prop_neither = volume_neither/volume_total)

#trying to get R to count the number of times each prey category is consumed by each individual salamander to replicate the GLM that had significant results
#I want to get R to do this, but for the sake of getting this analysis done, I am uploading the csv
#dietnumber <- saldata_raw %>%
 # filter(SAMPLING.METHOD %in% c('Flushed')) %>%
  #filter(!TAXA %in% c('Unidentifiable Insect Parts', 'No gut contents')) %>%
  #group_by(SITE, SEASON, SPECIES, SVL, SPECIMEN.ID, PREY.CATEGORY) %>%
  #group_by()


prey_category_count <- saldata_raw %>%
  filter(SAMPLING.METHOD %in% c('Flushed')) %>%
  filter(!TAXA %in% c('Unidentifiable Insect Parts', 'No gut contents')) %>%
  group_by(SITE, SEASON, SPECIES, SVL, SPECIMEN.ID, PREY.CATEGORY) %>%
  summarize(n = n()) %>%
  pivot_wider(names_from = PREY.CATEGORY, 
              values_from = n,
              values_fill = 0,
              names_prefix = "count_") %>%
  mutate(count_total = sum(c_across(starts_with("count")), na.rm=T)) %>%
  mutate(propcount_aquatic = count_aquatic/count_total, 
         propcount_terrestrial = count_terrestrial/count_total, 
         propcount_intermediate = count_intermediate/count_total, 
         propcount_neither = count_neither/count_total)
```


workflow for background sample count by prey category comparison
```{r}
#keep counts from prey_category_count
#group by season
#sum total number prey eaten within each category for each season

prey_count_totals <- prey_category_count %>%
  group_by(SEASON) %>%
  summarize(total_aquatic = sum(count_aquatic),
            total_terrestrial = sum(count_terrestrial),
            total_intermediate = sum(count_intermediate),
            total_neither = sum(count_neither))


#from background samples
#group by season
#sum total number prey items observed from each prey category for each season

#need to add prey category to BGS MASTER LIST, will proceed from here when updated
background <- read.csv("BGS MASTER LIST.csv")

#get total prey eaten (sum of all categories) from salamanders - per season
#get total prey items documented (sum of all categories) from background - per season
#get proportion of total prey items documented from each category (prop of total) - per season


#calculate 'expected' number of prey eaten based on the total documented and category proportions

#chi squared - salamander diets are observed, background estimated counts from proportions are expected
```


#stats

```{r stats}
kruskal.test(SVL ~ SPECIES,
             data = SVL)

#KW examining volume of prey cat consumed as a function of SPECIES

#aquatic
kruskal.test(volume_aquatic ~ SPECIES,
             data = dietvolume_by_preycategory)

dunnTest(volume_aquatic ~ SPECIES,
         data = dietvolume_by_preycategory)

#intermediate
kruskal.test(volume_intermediate ~ SPECIES,
             data = dietvolume_by_preycategory)

dunnTest(volume_intermediate ~ SPECIES,
         data = dietvolume_by_preycategory)

#terrestrial
kruskal.test(volume_terrestrial ~ SPECIES,
             data = dietvolume_by_preycategory)

dunnTest(volume_terrestrial ~ SPECIES,
         data = dietvolume_by_preycategory)

#neither
kruskal.test(volume_neither ~ SPECIES,
             data = dietvolume_by_preycategory)

dunnTest(volume_neither ~ SPECIES,
         data = dietvolume_by_preycategory)


#KW examining volume of prey cat consumed as a function of SVL
#running a dunn test using SVL seems like a lot?

#aquatic
kruskal.test(volume_aquatic ~ SVL,
             data = dietvolume_by_preycategory)

dunnTest(volume_aquatic ~ SVL,
         data = dietvolume_by_preycategory)

#intermediate
kruskal.test(volume_intermediate ~ SVL,
             data = dietvolume_by_preycategory)

#terrestrial
kruskal.test(volume_terrestrial ~ SVL,
             data = dietvolume_by_preycategory)

#neither
kruskal.test(volume_neither ~ SVL,
             data = dietvolume_by_preycategory)


#KW examining % number of prey cat consumed as a function of SEASON
kruskal.test(propcount_aquatic ~ SEASON,
             data = prey_category_count)


dunnTest(propcount_aquatic ~ SEASON,
         data = prey_category_count)


#feels like species should be represented somehow, even though there was no significant difference in proportion aquatic prey consumed between species..
ggplot(dietnumber,
  aes(x = season, y = percent.aquatic)) +
  geom_jitter(width = 0.01, size = 8, alpha = 0.1,) +
  ggtitle("Aquatic Prey Volume")
  
#KW looking at NUMBER of prey cat consumed as function of SPECIES
kruskal.test(count_aquatic ~ SPECIES,
             data = prey_category_count)

dunnTest(propcount_aquatic ~ SPECIES,
         data = prey_category_count)

kruskal.test(count_intermediate ~ SPECIES,
             data = prey_category_count)

dunnTest(propcount_intermediate ~ SPECIES,
         data = prey_category_count)

kruskal.test(count_terrestrial ~ SPECIES,
             data = prey_category_count)

dunnTest(propcount_terrestrial ~ SPECIES,
         data = prey_category_count)

```

```{r GLM on percent aquatic prey volume}

#still not significant and I think I figured out why. I think the file "diet ANOVA % aquatic" was originally used to run the GLM that gave significant results, and that was based on the NUMBER of each type of prey consumed, not the VOLUME.

volume_glm <- car::Anova(glm(formula = prop_aquatic ~ SPECIES + SVL + SEASON,
                      data = volume_diet_prop, family = binomial), type = 3)


#uploaded that CSV and running GLM code on the proportion of NUMBER of prey type consumed
#can't run with SVL because this was formatted from a pivot table using size class, need to get R to make this dataset but don't have time to figure it out right now

number_glm <- car::Anova(glm(formula = propcount_aquatic ~ SPECIES + SVL + SEASON,
                      data = prey_category_count, family = binomial), type = 3)

```